package cz.muni.fi.pv168.brewerymanager.gui;

import cz.muni.fi.pv168.brewerymanager.backend.Employee;
import cz.muni.fi.pv168.brewerymanager.backend.Position;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adam
 */
public class EmployeeFrame extends javax.swing.JFrame {
    private static final ResourceBundle texts = ResourceBundle.getBundle("gui/texts");
    private final EmployeeTableModel employeeModel;
    /**
     * Creates new form EmployeeFrame
     */
    public EmployeeFrame(EmployeeTableModel employeeModel) {
        initComponents();
        this.employeeModel = employeeModel;
    }
    
        private void actionAddEmployee(){
        String name = jTextFieldName.getText();
        String email = jTextFieldEmail.getText();
        String phoneNumber = jTextFieldPhoneNumber.getText();
        String salary = jTextFieldSalary.getText(); 
        Position position = (Position)jComboBoxPosition.getSelectedItem();         
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE NAME"), texts.getString("NAME REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE EMAIL"), texts.getString("EMAIL REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE EMAIL"), texts.getString("EMAIL REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, texts.getString("YOU HAVE TO ENTER THE PHONE NUMBER"), texts.getString("PHONE NUMBER REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;
        }
                
        
        int salaryInt;
        try {
           salaryInt = Integer.parseInt(salary);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, texts.getString("WRONG FORMAT OF SALARY"), texts.getString("SALARY REQUIRED"), JOptionPane.WARNING_MESSAGE);
            return;            
        }
        
        Employee employee = new Employee();
        employee.setName(name);
        employee.setEmail(email);
        employee.setPhoneNumber(phoneNumber);
        employee.setPosition(position);
        employee.setSalary(salaryInt);
        employeeModel.addRow(employee, employeeModel); 
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAdd = new javax.swing.JButton();
        jComboBoxPosition = new javax.swing.JComboBox();
        jTextFieldSalary = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelSalary = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/texts_cs_CZ"); // NOI18N
        jButtonAdd.setText(bundle.getString("ADD")); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jComboBoxPosition.setModel(new DefaultComboBoxModel(Position.values()));

        jTextFieldSalary.setToolTipText(texts.getString("SALARY OF EMPLOYEE"));

        jTextFieldPhoneNumber.setToolTipText(texts.getString("PHONE NUMBER OF EMPLOYEE"));

        jTextFieldEmail.setToolTipText(texts.getString("EMAIL OF EMPLOYEE"));

        jTextFieldName.setToolTipText(texts.getString("NAME OF EMPLOYEE"));
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("NAME:")); // NOI18N

        jLabelEmail.setText(bundle.getString("EMAIL:")); // NOI18N

        jLabelPhoneNumber.setText(bundle.getString("PHONE NUMBER:")); // NOI18N

        jLabelSalary.setText(bundle.getString("SALARY:")); // NOI18N

        jLabelPosition.setText(bundle.getString("POSITION:")); // NOI18N

        jButtonCancel.setText(bundle.getString("CANCEL")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jLabelPosition)
                    .addComponent(jLabelSalary)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldName)
                    .addComponent(jTextFieldPhoneNumber)
                    .addComponent(jTextFieldSalary)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosition)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        actionAddEmployee();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldSalary;
    // End of variables declaration//GEN-END:variables
}
