package cz.muni.fi.pv168.brewerymanager.gui;

import cz.muni.fi.pv168.brewerymanager.backend.Employee;
import cz.muni.fi.pv168.brewerymanager.backend.Keg;
import cz.muni.fi.pv168.brewerymanager.backend.Work;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author adam
 */
public class WorkFrame extends javax.swing.JFrame {
    private static final ResourceBundle texts = ResourceBundle.getBundle("gui/texts");
    private final WorkTableModel workModel;
    private final EmployeeTableModel employeeModel;
    private final KegTableModel kegModel;    
    /**
     * Creates new form WorkFrame
     */
    public WorkFrame(WorkTableModel workModel, EmployeeTableModel employeeModel, KegTableModel kegModel) {
                this.workModel = workModel;
        this.employeeModel = employeeModel;
        this.kegModel = kegModel;
        
        initComponents();
        
                
        TableColumn columnEmpEmail = jTableEmployees.getColumn(jTableEmployees.getColumnName(2));
        jTableEmployees.getColumnModel().removeColumn(columnEmpEmail);
        TableColumn columnEmpSalary = jTableEmployees.getColumn(jTableEmployees.getColumnName(3));
        jTableEmployees.getColumnModel().removeColumn(columnEmpSalary);
        
        
        TableColumn columnKegPrice = jTableKegs.getColumn(jTableKegs.getColumnName(2));
        jTableKegs.getColumnModel().removeColumn(columnKegPrice);
        TableColumn columnKegDeposit = jTableKegs.getColumn(jTableKegs.getColumnName(3));
        jTableKegs.getColumnModel().removeColumn(columnKegDeposit);
    }
    
    private void actionStartWork(){
       Long employeeId = (Long)kegModel.getValueAt(jTableKegs.getSelectedRow(), 1);
       Long kegId = (Long)employeeModel.getValueAt(jTableEmployees.getSelectedRow(), 0);
       Work work = new Work();
       work.setEmployeeId(employeeId);
       work.setKegId(kegId);
        workModel.addRow(work, employeeId, kegId, workModel);
        this.dispose();
    }
    private void actionCancel(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStartWork = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployees = new javax.swing.JTable();
        jButtonCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKegs = new javax.swing.JTable();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("gui/texts_cs_CZ"); // NOI18N
        jButtonStartWork.setText(bundle.getString("STARTWORK")); // NOI18N
        jButtonStartWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartWorkActionPerformed(evt);
            }
        });

        jTableEmployees.setModel(employeeModel);
        jScrollPane1.setViewportView(jTableEmployees);

        jButtonCancel.setText(bundle.getString("CANCEL")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTableKegs.setModel(kegModel);
        jScrollPane2.setViewportView(jTableKegs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButtonStartWork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStartWork)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      actionCancel();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonStartWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartWorkActionPerformed
        actionStartWork();
    }//GEN-LAST:event_jButtonStartWorkActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonStartWork;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmployees;
    private javax.swing.JTable jTableKegs;
    // End of variables declaration//GEN-END:variables
}
