CREATE TABLE "KEG" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CAPACITY" INTEGER NOT NULL,
    "PRICE" INTEGER NOT NULL,
    "DEPOSIT" INTEGER NOT NULL,
    "BRAND" VARCHAR(255)
);

CREATE TABLE "EMPLOYEE" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "PHONENUMBER" VARCHAR(255) NOT NULL,
    "SALARY" INTEGER NOT NULL,
    "POSITION" VARCHAR(30) NOT NULL 
);

CREATE TABLE "JOB" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "EMPLOYEE_ID" BIGINT NOT NULL,
    "KEG_ID" BIGINT NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "START_TIME" TIME NOT NULL,
    "END_TIME"  TIME,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (KEG_ID) REFERENCES KEG(ID)
);